---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    jenkins: master
  ports:
    - name: http
      port: 8080
    - name: jnlp
      port: 50000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jenkins-master
 annotations:
   volume.beta.kubernetes.io/storage-class: default
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        jenkins: master
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "busybox:latest",
            "command": [ "sh", "-c", "chown 1000:1000 /var/jenkins_home" ],
            "volumeMounts": [
              { "name": "data", "mountPath": "/var/jenkins_home" }
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: jenkins
        image: henryrao/jenkins-kubernetes:0.1
        ports:
          - containerPort: 8080
          - containerPort: 50000
        volumeMounts:
          - name: data
            mountPath: /var/jenkins_home
        env:
          - name: TRY_UPGRADE_IF_NO_MARKER
            value: "true"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jenkins-master
