---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "jenkins-master-jobs"
  annotations:
    volume.beta.kubernetes.io/storage-class: "default"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
