---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        jenkins: {{ printf "master-%s" .Release.Name | trunc 63 }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "busybox:latest",
            "command": [ "sh", "-c", "chown 1000:1000 /var/jenkins_home/jobs" ],
            "volumeMounts": [
              { "name": "jobs", "mountPath": "/var/jenkins_home/jobs" }
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: jenkins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.internalPort }}
          - containerPort: {{ .Values.service.jnlpPort }}
        volumeMounts:
          - name: jobs
            mountPath: /var/jenkins_home/jobs
          - name: jenkins-credentials
            mountPath: /usr/share/jenkins/ref/init.groovy.d/credentials.groovy
            subPath: credentials.groovy
          - name: docker-sock
            mountPath: /var/run/docker.sock
        env:
          - name: TRY_UPGRADE_IF_NO_MARKER
            value: "true"
          - name: JAVA_OPTS
            value: "-Xmx512m -Xms512m"
      volumes:
        - name: jobs
          persistentVolumeClaim:
            claimName: {{ printf "jenkins-master-job-pvc-%s" .Release.Name | trunc 63 }}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - configMap:
            name: {{ printf "jenkins-credentials-%s" .Release.Name | trunc 63 }}
          name: jenkins-credentials
