---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jenkins-master-jobs
 annotations:
   volume.beta.kubernetes.io/storage-class: default
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
