apiVersion: "v1"
kind: "Pod"
metadata:
  name: "sbt-jnlp-slave"
  labels:
    name: "sbt-jnlp-slave"
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
      {
            "name": "init",
            "image": "busybox:latest",
            "command": [ "sh", "-c", "chown 10000:10000 /home/jenkins" ],
            "volumeMounts": [
              { "name": "data", "mountPath": "/home/jenkins" }
            ],
            "imagePullPolicy": "IfNotPresent"
      }
    ]'
spec:
  containers:
    - name: "sbt-jnlp-slave"
      image: "henryrao/sbt-jnlp-slave:latest"
      env:
        - name: "JENKINS_URL"
          value: "http://jenkins.default.svc.cluster.local:8080"
      volumeMounts:
        - name: data
          mountPath: /home/jenkins
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: sbt-env
