---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}    
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ include "labels.master" . | indent 8 }}
      annotations:
        checksum/jenkins-config: {{ include (print $.Template.BasePath "/jenkins-configMap.yaml") . | sha256sum }}
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "busybox:latest",
            "command": [ "sh", "-c", "chown 1000:1000 {{ .Values.volumes.jobs.mountPath }}" ],
            "volumeMounts": [
              { "name": "jobs", "mountPath": "{{ .Values.volumes.jobs.mountPath }}" }
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: jenkins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.http.port }}
          - name: jnlp
            containerPort: {{ .Values.service.jnlp.port }}
        volumeMounts:
          - name: jobs
            mountPath: {{ .Values.volumes.jobs.mountPath }}
          - name: configs
            mountPath: /usr/share/jenkins/ref/init.groovy.d/credentials.groovy
            subPath: credentials.groovy
          - name: configs
            mountPath: /usr/share/jenkins/ref/init.groovy.d/kubernetes.groovy
            subPath: kubernetes.groovy
          - name: configs
            mountPath: /usr/share/jenkins/ref/init.groovy.d/create-seed-job.groovy
            subPath: create-seed-job.groovy
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: secrets
            mountPath: /var/jenkins_home/.ssh
        env:
          - name: TRY_UPGRADE_IF_NO_MARKER
            value: "true"
          - name: JAVA_OPTS
            value: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Taipei -Djenkins.install.runSetupWizard=false {{ .Values.mem.heapSize }}"
      volumes:
        - name: jobs
          persistentVolumeClaim:
            claimName: {{ template "volumes.jobs" . }}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - configMap:
            name: {{ template "fullname" . }}
          name: configs
        - configMap:
            name: {{ template "fullname" . }}-secrets
          name: secrets
