{{- $relname := .Release.Name -}}
{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ printf "jenkins-master-%s-%s" .name $relname | trunc 63 }}
 annotations:
   volume.beta.kubernetes.io/storage-class: {{ .storageClass }}
spec:
 accessModes:
  - {{ .accessModes }}
 resources:
   requests:
     storage: {{ .size }}
{{- end }}
