---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "volumes.jobs" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    {{- if .Values.volumes.jobs.keep }}
    "helm.sh/resource-policy": keep
    {{- end}}
    volume.beta.kubernetes.io/storage-class: {{ .Values.volumes.jobs.storageClass }}
spec:
  accessModes:
  - {{ .Values.volumes.jobs.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.jobs.size }}
