---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Chart.Name .Release.Name | trunc 63 }}
spec:
  type: NodePort
  selector:
    jenkins: {{ printf "master-%s" .Release.Name | trunc 63 }}
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
    - name: jnlp
      port: {{ .Values.service.jnlpPort }}
