---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ printf "jenkins-master-jobs-%s" .Release.Name | trunc 63 }}
 annotations:
   volume.beta.kubernetes.io/storage-class: default
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 5Gi
