---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Chart.Name .Release.Name | trunc 63 }}
spec:
  type: NodePort
  selector:
    jenkins: {{ printf "master-%s" .Release.Name | trunc 63 }}
    app: {{ .Chart.Name }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
{{- end }}
