---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "jenkins-credentials-%s" .Release.Name | trunc 63 }}
data:
  credentials.groovy: |
    import com.cloudbees.plugins.credentials.impl.*;
    import com.cloudbees.plugins.credentials.*;
    import com.cloudbees.plugins.credentials.domains.*;
    Credentials c = (Credentials) new UsernamePasswordCredentialsImpl(CredentialsScope.GLOBAL,"docker-login", "public docker hub account", "{{ .Values.configMap.dockerHub.username }}", "{{ .Values.configMap.dockerHub.password }}")
    SystemCredentialsProvider.getInstance().getStore().addCredentials(Domain.global(), c)
