---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}    
spec:
  type: NodePort
  selector:
{{ include "labels.master" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
    - name: jnlp
      port: {{ .Values.service.jnlp.port }}