---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
{{ include "labels" . | indent 4 }}
data:
  {{ required "A valid .Values.gitlab.name entry required!" .Values.gitlab.name }}: |-
{{ required "A valid .Values.gitlab.key entry required!" .Values.gitlab.key | indent 4 }}