---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: sbt-env
 annotations:
   volume.beta.kubernetes.io/storage-class: default
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
