# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: henryrao/jenkins-kubernetes
  tag: 2.46.2
  pullPolicy: Always
service:
  ports:
    - name: http
      port: 8080
    - name: jnlp
      port: 50000
mem:
  heapSize: "-Xmx512m -Xms512m"
configMap:
  dockerHub:
    username: docker
    password: docker
volumes:
  - name: jobs
    storageClass: default
    size: 2Gi
    accessModes: ReadWriteMany
    mountPath: /var/jenkins_home/jobs
