# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: henryrao/jenkins-kubernetes
  tag: ${BUILD_TAG}
  pullPolicy: Always
service:
  http:
    port: 8080
  jnlp:
    port: 50000
mem:
  heapSize: "-Xmx1024m -Xms1024m"
volumes:
  jobs:
    storageClass: default
    size: 2Gi
    accessModes: ReadWriteOnce
    mountPath: /var/jenkins_home/jobs
caches:
  helm:
    name: helm-repository 
    storageClass: default
    size: 1Gi
    accessModes: ReadWriteOnce
    enabled: true
  ivy2:
    name: jenkins-ivy2 
    storageClass: default
    size: 2Gi
    accessModes: ReadWriteOnce
    enabled: true
seedjob:
  url: ssh://git@rd.grandsys.com:8687/henry.jao/seedjob.git
  credentials: gitlab-inu
users:
  - name: admin
    passwd: admin
dockerHub:
  username: '???'
  password: '???'
helmRepo:
  username: '???'
  password: '???'
gitlab:
  credentialsId: gitlab-inu
  username: gitlab
  passphrase: '???'
  name: 'gitlab_inu_rsa'
  key: '-----BEGIN RSA PRIVATE KEY-----' 
volumePolicy: 'drop'
