# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: henryrao/jenkins-kubernetes
  tag: 2.46.2
  pullPolicy: Always
service:
  http:
    port: 8080
  jnlp:
    port: 50000
mem:
  heapSize: "-Xmx256m -Xms256m"
volumes:
  jobs:
    storageClass: default
    size: 2Gi
    accessModes: ReadWriteMany
    mountPath: /var/jenkins_home/jobs
seedjob:
  url: ssh://git@rd.grandsys.com:8687/henry.jao/seedjob.git
  credentials: gitlab-inu
dockerHub:
  username: ''
  password: ''
helmRepo:
  username: ''
  password: ''
gitlab:
  credentialsId: gitlab-inu
  username: gitlab
  passphrase: ''
  name: 'gitlab_inu_rsa'
  key: '' 


