# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.grandsys.com/jenkins/jenkins
  tag: ${BUILD_TAG}
  pullPolicy: Always
service:
  http:
    port: 8080
  jnlp:
    port: 50000
mem:
  heapSize: "-Xmx1024m -Xms1024m"
footerUrl: https://www.grandsys.com.tw
volumes:
  jobs:
    storageClass: default
    size: 2Gi
    accessModes: ReadWriteOnce
    mountPath: /var/jenkins_home/jobs
    keep: false
caches:
  - name: helm-repository
    storageClass: default
    size: 1Gi
    accessModes: ReadWriteOnce
    enabled: true
    keep: false
  - name: jenkins-ivy2
    storageClass: default
    size: 2Gi
    accessModes: ReadWriteOnce
    enabled: true
    keep: false
seedjob:
  url: ssh://git@rd.grandsys.com:8687/henry.jao/seedjob.git
  credentials: gitlab-inu
envs:
  - name: HELM_IMAGE
    value: docker.grandsys.com/library/helm:2.6.1
  - name: PRIVATE_REGISTRY_URL
    value: 'https://docker.grandsys.com/v2/'
  - name: PRIVATE_REGISTRY
    value: docker.grandsys.com
  - name: JNLP_SLAVE_IMAGE
    value: docker.grandsys.com/jenkins/jnlp-slave:3.7
  - name: HELM_PUBLIC_REPO_URL
    value: https://grandsys.github.io/helm-repository/
  - name: GOLANG_VER
    value: "1.8.3"
  - name: GOPATH
    value: "/go"
users:
  - name: henry
    passwd: henry
adminUser: admin
adminPasswd: admin
dockerRegistry:
  username: '???'
  password: '???'
helmRepo:
  username: '???'
  password: '???'
gitlab:
  credentialsId: gitlab-inu
  username: gitlab
  passphrase: '???'
  name: 'gitlab_inu_rsa'
  key: '-----BEGIN RSA PRIVATE KEY-----' 
